blank_issues_enabled: true
contact_links:
  - name: Project Documentation
    url: https://celerium.github.io/Celerium.FanartTV/
    about: Read through the generated documentation
  - name: Vendor Documentation
    url: https://api.FanartTV.com/developer
    about: Read through the vendors documentation